### ISSUE TITLE
Loading town12 map into CARLA stimulator

### ISSUE THREAD

**Issue by viola521** [viola521/LAV-main#1]
how could I fix the problem of loading town12 map into CARLA stimulator?
I downloaded the additional map zip for CARLA 0.9.14
and copy the town12 folder into my original folder of maps 
and configure.py -m Twon12 
the map showed as below....
![Screenshot from 2023-07-08 13-18-46](https://github.com/viola521/LAV-main/assets/136361931/2b28a074-f401-4dcf-b156-011981882634)

**Comment by wuhanstudio** [comment]
Please follow the official documentation to change the map:

https://carla.readthedocs.io/en/latest/core_map/

**Comment by viola521** [comment]
Hi,both                             
could I not use the town12 map ?when I saw the configuration require which need 700G storage of computer,
I installed tow systems and just have 100G+,could I have some instead solution for evaluation.
I want to run_evaluattion.py
![Screenshot from 2023-07-12 13-09-20](https://github.com/viola521/LAV-main/assets/136361931/122e8a27-7e71-4d33-9123-4620033e3ac9)
https://carla.readthedocs.io/en/latest/tuto_M_add_map_package/

**Comment by wuhanstudio** [comment]
Please follow the documentation as I suggested here:

https://carla.readthedocs.io/en/latest/core_map/

The map can be loaded using a single line of code:
```
world = client.load_world('Town12')
```
After loading the Town 12, you will only see an empty scene because it is a tiled map. The tiles will only be loaded with the vehicle moving through them, which means you must spawn an ego vehicle to see the map.

**Comment by viola521** [comment]
![Screenshot from 2023-07-12 18-47-19](https://github.com/viola521/LAV-main/assets/136361931/3b5b8a65-818e-4219-a79e-e2dd69851658)
![Screenshot from 2023-07-12 18-46-15](https://github.com/viola521/LAV-main/assets/136361931/5020dda5-015e-4710-9a77-64647a406a8a)
![Screenshot from 2023-07-12 18-51-15](https://github.com/viola521/LAV-main/assets/136361931/65e3bd87-9804-4f34-88c0-df2340949b08)

**Comment by viola521** [comment]
> Please follow the documentation as I suggested here:
> 
> https://carla.readthedocs.io/en/latest/core_map/
> 
> The map can be loaded using a single line of code:
> 
> ```
> world = client.load_world('Town12')
> ```
> 
> After loading the Town 12, you will only see an empty scene because it is a tiled map. The tiles will only be loaded

 with the vehicle moving through them, which means you must spawn an ego vehicle to see the map.

I have use configure.py -m Town12 to load map 
and use example/generate_traffic.py to spawn vehicle,but the map still didn't go well. 



![Screenshot from 2023-07-12 20-51-21](https://github.com/viola521/LAV-main/assets/136361931/7047b941-b713-45df-97ce-199c9c13bb93)

**Comment by wuhanstudio** [comment]
Since the example `example/generate_traffic.py` only generates traffic rather than an ego vehicle, you will still see an empty map. This example spawns an ego vehicle:

```
python config.py -m Town12
python manual_control.py
```

![Screenshot from 2023-07-12 21-55-26](https://github.com/viola521/LAV-main/assets/15157070/817fab7e-a013-4ec9-a07e-8515be877b9d)

**Comment by viola521** [comment]
> Since the example `example/generate_traffic.py` only generates traffic rather than an ego vehicle, you will still see an empty map. This example spawns an ego vehicle:
> 
> ```
> python config.py -m Town12
> python manual_control.py
> ```
> 
> ![Screenshot from 2023-07-12 21-55-26](https://user-images.githubusercontent.com/15157070/253098725-817fab7e-a013-4ec9-a07e-8515be877b9d.png)

so if I run the evalution in leaderboard,it occurs error : 

/bin/bash /home/violayu/disk2/LAV-main/leaderboard/scripts/run_evaluation.sh



if LooseVersion(dist.version) < LooseVersion('0.9.10'):

========= Preparing RouteScenario_0 (repetition 0) =========
Loading the world
~~~~~~~~~~~~~~~~~ Town12
<srunner.scenarioconfigs.route_scenario_configuration.RouteScenarioConfiguration object at 0x7f6f0880b580>
[<carla.libcarla.Location object at 0x7f6dcb5c06f0>, <carla.libcarla.Location object at 0x7f6dcb5c0670>, <carla.libcarla.Location object at 0x7f6dcb5c04f0>, <carla.libcarla.Location object at 0x7f6dcb5c03b0>, <carla.libcarla.Location object at 0x7f6dcb87cf30>, <carla.libcarla.Location object at 0x7f6dc5afd3b0>, <carla.libcarla.Location object at 0x7f6dc5afd3f0>, <carla.libcarla.Location object at 0x7f6dc5afd430>, <carla.libcarla.Location object at 0x7f6dc5afd470>, <carla.libcarla.Location object at 0x7f6e67c8a230>, <carla.libcarla.Location object at 0x7f6dc5afd4b0>, <carla.libcarla.Location object at 0x7f6dc5afd4f0>, <carla.libcarla.Location object at 0x7f6dc5afd530>, <carla.libcarla.Location object at 0x7f6dc5afd570>, <carla.libcarla.Location object at 0x7f6dc5afd5b0>, <carla.libcarla.Location object at 0x7f6dc5afd5f0>, <carla.libcarla.Location object at 0x7f6dc5afd630>, <carla.libcarla.Location object at 0x7f6dc5afd670>, <carla.libcarla.Location object at 0x7f6dc5afd6b0>, <carla.libcarla.Location object at 0x7f6dc5afd6f0>, <carla.libcarla.Location object at 0x7f6dc5afd730>, <carla.libcarla.Location object at 0x7f6dc5afd770>, <carla.libcarla.Location object at 0x7f6dc5afd7b0>, <carla.libcarla.Location object at 0x7f6dc5afd7f0>, <carla.libcarla.Location object at 0x7f6dc5afd830>, <carla.libcarla.Location object at 0x7f6dc5afd870>, <carla.libcarla.Location object at 0x7f6dc5afd8b0>, <carla.libcarla.Location object at 0x7f6dc5afd8f0>, <carla.libcarla.Location object at 0x7f6dc5afd930>, <carla.libcarla.Location object at 0x7f6dc5afd970>, <carla.libcarla.Location object at 0x7f6dc5afd9b0>, <carla.libcarla.Location object at 0x7f6dc5afd9f0>, <carla.libcarla.Location object at 0x7f6dc5afda30>, <carla.libcarla.Location object at 0x7f6dc5afda70>, <carla.libcarla.Location object at 0x7f6dc5afdab0>]

The scenario could not be loaded:

Traceback (most recent call last):
  File "/home/violayu/disk2/LAV-main/leaderboard/leaderboard/leaderboard_evaluator.py", line 271, in _load_and_run_scenario
    self.route_scenario = RouteScenario(world=self.world, config=config, debug_mode=args.debug)
  File "/home/violayu/disk2/LAV-main/leaderboard/leaderboard/scenarios/route_scenario.py", line 71, in __init__
    self.route = self._get_route(config)
  File "/home/violayu/disk2/LAV-main/leaderboard/leaderboard/scenarios/route_scenario.py", line 124, in _get_route
    self.gps_route, self.route = interpolate_trajectory(config.keypoints)
  File "/home/violayu/disk2/LAV-main/leaderboard/leaderboard/utils/route_manipulation.py", line 146, in interpolate_trajectory
    grp = GlobalRoutePlanner(CarlaDataProvider.get_map(), hop_resolution)
  File "/home/violayu/disk2/LAV-main/leaderboard/leaderboard/srunner/scenariomanager/carla_data_provider.py", line 234, in get_map
    raise ValueError("class member \'world'\' not initialized yet")
ValueError: class member 'world'' not initialized yet

> Registering the route statistics
Exception ignored in: <function RouteScenario.__del__ at 0x7f6f090643a0>
Traceback (most recent call last):
  File "/home/violayu/disk2/LAV-main/leaderboard/leaderboard/scenarios/route_scenario.py", line 496, in __del__
    self.client.apply_batch([carla.command.DestroyActor(x) for x in self._parked_ids])
AttributeError: 'RouteScenario' object has no attribute '_parked_ids'
(base) violayu@violayu-Dell-G15-5520:~/disk2/LAV-main/leaderboard/scripts$ 

but when I check the routes_training.xml ,I saw there was waypoint in the the file of configuration .
![Screenshot from 2023-07-13 10-28-37](https://github.com/viola521/LAV-main/assets/136361931/6a10d2d8-cd90-4527-85e2-4a648d087ffe)

**Comment by viola521** [comment]
![Screenshot from 2023-07-13 10-28-37](https://github.com/viola521/LAV-main/assets/136361931/b95fd6bf-220a-44ad-bfb6-24fb1b3db6c0)
but when I check the routes_training.xml ,I saw there was waypoint in the the file of configuration .
